# Generated by Django 3.2.6 on 2023-03-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0017_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='TimeSlots',
            field=models.JSONField(default=[]),
        ),
    ]
