# Generated by Django 3.2.6 on 2023-03-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0018_appointment_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Time',
        ),
    ]
