# Generated by Django 3.2.6 on 2023-03-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0019_remove_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='TimeSlots',
            field=models.CharField(max_length=50),
        ),
    ]
