# Generated by Django 3.2.10 on 2023-03-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0020_alter_appointment_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='RequestStatus',
        ),
    ]
