# Generated by Django 3.2.6 on 2023-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0021_remove_appointment_requeststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
