# Generated by Django 3.2.6 on 2023-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0022_alter_appointment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Email',
            field=models.CharField(default='Not provided', max_length=50),
        ),
    ]
