# Generated by Django 3.2.6 on 2023-07-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0024_doctorleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='doctor_name',
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='leave_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VR_Chest_App.doctor'),
        ),
    ]
